name: openFDA
url: https://open.fda.gov

markdown: kramdown
kramdown:
  enable_coderay: true
  coderay_line_numbers: nil
  parse_block_html: true

highlighter: pygments
permalink: /update/:title/
baseurl: ""
apiurl: https://api.fda.gov
